### ISSUE TITLE
Duplicate names

### ISSUE THREAD

**Issue by wfaguy** [ffeldhaus/S3-Client#1]
When having S3-client & AWS tools for windows open at the same time, there is a collision in commandnames.  Some are duplicates.  Now, I see in your S3 client you use pure powershell (invoke-webrequest), which is by default not sending in chunks and fails for largers files.  Therefor the write-s3object of AWS is better and more performant.  But installing the storagegrid module, also installs the the s3-client modules, which breaks the AWS module.  In powershell you can use default prefix when exporting functions, which I would advise.

**Comment by ffeldhaus** [comment]
With the release of a separate S3-Client Module everyone now can decide which one to use. The next StorageGRID Cmdlet Release will remove the bundled S3-Client.

This S3 Client now also supports S3 Multipart Uploads and should be at least as fast as the official AWS S3 PowerShell Cmdlets.
