### ISSUE TITLE
Improve doc -> Installation on Windows 2016

### ISSUE THREAD

**Issue by mschindl** [ffeldhaus/S3-Client#2]
Feedback to the installation howto:

- Get-Module gives no response
- Import-Module seems only to work after select psd1/psm1 file (three different import cmds worked? I think one is enough)

![Foto1](https://user-images.githubusercontent.com/26382876/43582420-b100a60c-965c-11e8-949d-1246d416f8ca.png)

![Foto2](https://user-images.githubusercontent.com/26382876/43582489-ed1d97b2-965c-11e8-87d7-5752106d600e.png)

**Comment by ffeldhaus** [comment]
Did you follow the instructions for [Installation from the README](https://github.com/ffeldhaus/S3-Client#installation)? It is important that you download the S3-Client.zip file from the [Release page](https://github.com/ffeldhaus/S3-Client/releases/latest) and do not download the source code. The content of the zip file must be extracted to the PowerShell Module path (you can check the available Module paths with `[Environment]::GetEnvironmentVariable("PSModulePath")`). Then a `Get-Module -ListAvailable S3-Client` should show the S3-Module and `Import-Module S3-Client` should work fine (and shouldn't even be necessary after restarting PowerShell as all modules in the Module path get automatically loaded when you use a Cmdlet from them).

**Comment by mschindl** [comment]
Upgrade to newer Version solved the issue.

> Install-Module -Name S3-Client
> Update-Module s3-client
> Uninstall-Module s3-client -RequiredVersion 1.3.0
optional> Import-Module S3-Client -Force
