### ISSUE TITLE
Response Versioning Disabled missing

### ISSUE THREAD

**Issue by mschindl** [ffeldhaus/S3-Client#7]
PS /Users/marc> Get-S3BucketVersioning -ProfileName SGCBC -BucketName marc-bucket-versioning
Enabled                                                                             
PS /Users/marc> Get-S3BucketVersioning -ProfileName SGCBC -BucketName marc-bucket-repl-aws  
**No response**

**Comment by ffeldhaus** [comment]
This is the correct behavior. A bucket by default is "unversioned" and the versioning status is just empty. Bucket versioning can then be enabled and suspended, but never disabled.

See https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html for details.
